package generator

import (
	"fmt"
	"strings"

	"CodeX/parser"
)

// scopeEntry описывает одну переменную в области видимости.
type scopeEntry struct {
	name       string // имя переменной
	structName string // имя структуры (пусто для примитивов)
	cType      string // C-тип переменной (int, float, char*, Player*...)
	isParam    bool   // true если это параметр функции — не удалять через RAII
}

// Generator генерирует Си-код из AST.
type Generator struct {
	output      strings.Builder
	indent      int
	scopeStack  [][]scopeEntry
	destructors map[string]bool
}

// New создаёт новый генератор.
func New() *Generator {
	g := &Generator{
		destructors: make(map[string]bool),
	}
	g.scopeStack = append(g.scopeStack, []scopeEntry{})
	return g
}

// Generate обходит корень AST и возвращает сгенерированный Си-код.
func (g *Generator) Generate(program *parser.ASTNode) (string, error) {
	g.emitLine("// Generated by CodeX compiler")
	g.emitLine("#include <stdlib.h>")
	g.emitLine("#include <stdio.h>")
	g.emitLine("")

	g.collectDestructors(program)

	for _, child := range program.Children {
		if err := g.genTopLevel(child); err != nil {
			return "", err
		}
	}

	return g.output.String(), nil
}

func (g *Generator) collectDestructors(node *parser.ASTNode) {
	if node == nil {
		return
	}
	if node.Type == parser.NodeStructDecl {
		for _, child := range node.Children {
			if child.Type == parser.NodeFnDecl && child.Name == "del" {
				g.destructors[node.Name] = true
			}
		}
	}
	for _, child := range node.Children {
		g.collectDestructors(child)
	}
}

// --- Генерация верхнего уровня ---

func (g *Generator) genTopLevel(node *parser.ASTNode) error {
	switch node.Type {
	case parser.NodeStructDecl:
		return g.genStructDecl(node)
	case parser.NodeFnDecl:
		return g.genFnDecl(node)
	}
	return nil
}

func (g *Generator) genStructDecl(node *parser.ASTNode) error {
	g.emitLine("typedef struct {")
	g.indent++
	for _, field := range node.Fields {
		cType := codexTypeToC(field.Value)
		g.emitLine("%s %s;", cType, field.Name)
	}
	g.indent--
	g.emitLine("} %s;", node.Name)
	g.emitLine("")

	for _, child := range node.Children {
		if child.Type == parser.NodeFnDecl && child.Name == "del" {
			g.emitLine("void %s_del(%s* self) {", node.Name, node.Name)
			g.indent++
			for _, stmt := range child.Body {
				g.genStmt(stmt)
			}
			g.indent--
			g.emitLine("}")
			g.emitLine("")
		}
	}
	return nil
}

func (g *Generator) genFnDecl(node *parser.ASTNode) error {
	g.pushScope()

	// Параметры помечаем isParam=true — RAII их не очищает
	for _, param := range node.Params {
		cType := codexTypeToC(param.Value)
		g.pushVar(param.Name, cType, true)
	}

	var paramParts []string
	for _, param := range node.Params {
		cType := codexTypeToC(param.Value)
		paramParts = append(paramParts, fmt.Sprintf("%s %s", cType, param.Name))
	}
	g.emitLine("void %s(%s) {", node.Name, strings.Join(paramParts, ", "))
	g.indent++

	for _, stmt := range node.Body {
		if err := g.genStmt(stmt); err != nil {
			return err
		}
	}

	// RAII: очищаем только локальные переменные (не параметры)
	g.emitDestructors()
	g.indent--
	g.emitLine("}")
	g.emitLine("")

	g.popScope()
	return nil
}

// --- Statement-генерирование ---

func (g *Generator) genStmt(node *parser.ASTNode) error {
	if node == nil {
		return nil
	}
	switch node.Type {
	case parser.NodeVarDecl:
		return g.genVarDecl(node)
	case parser.NodeCallExpr:
		return g.genCallExpr(node)
	case parser.NodeBlock:
		return g.genIfStmt(node)
	case parser.NodeFnDecl:
		return nil
	case parser.NodeFieldAccess:
		// Присваивание полю (уже обработано в genVarDecl как assign)
		return nil
	case parser.NodeIdent:
		return nil
	case parser.NodeNumber:
		return nil
	}
	return nil
}

// genVarDecl генерирует объявление переменной или присваивание.
func (g *Generator) genVarDecl(node *parser.ASTNode) error {
	// Присваивание через assign: node.Name == "assign", Children[0]=лево, Children[1]=право
	if node.Name == "assign" && len(node.Children) == 2 {
		left := g.exprToC(node.Children[0])
		right := g.exprToC(node.Children[1])
		g.emitLine("%s = %s;", left, right)
		return nil
	}

	var varType string
	var rhs string

	if node.Value != "" {
		varType = codexTypeToC(node.Value)
	}

	if len(node.Children) > 0 {
		rhs = g.exprToC(node.Children[0])
		if varType == "" {
			// Вывод типа из правой части
			if node.Children[0].Type == parser.NodeIdent {
				structName := node.Children[0].Name
				if _, ok := g.destructors[structName]; ok {
					varType = structName + "*"
					rhs = fmt.Sprintf("(%s*)malloc(sizeof(%s))", structName, structName)
				} else {
					varType = "int"
				}
			} else if node.Children[0].Type == parser.NodeNumber {
				if strings.Contains(node.Children[0].Value, ".") {
					varType = "float"
				} else {
					varType = "int"
				}
			} else if node.Children[0].Type == parser.NodeFieldAccess {
				// Вывод типа из поля (например temp := player.health)
				if strings.Contains(rhs, ".") {
					varType = "int"
				}
			}
		}
	}

	if varType != "" {
		g.emitLine("%s %s = %s;", varType, node.Name, rhs)
	} else {
		g.emitLine("%s = %s;", node.Name, rhs)
	}

	// Локальная переменная — не параметр
	g.pushVar(node.Name, varType, false)
	return nil
}

// genCallExpr генерирует вызов функции или метода.
func (g *Generator) genCallExpr(node *parser.ASTNode) error {
	if len(node.Children) == 0 {
		return nil
	}

	callee := node.Children[0]
	args := node.Children[1:]

	// Проверка на print — встроенная функция
	if callee.Type == parser.NodeIdent && callee.Name == "print" {
		return g.genPrintCall(args)
	}

	var callStr string
	switch callee.Type {
	case parser.NodeIdent:
		callStr = g.functionCallString(callee.Name, args)
	case parser.NodeFieldAccess:
		receiver := g.exprToC(callee.Children[0])
		method := callee.Name
		allArgs := append([]string{receiver}, g.argsToC(args)...)
		callStr = fmt.Sprintf("%s(%s)", method, strings.Join(allArgs, ", "))
	default:
		callStr = g.exprToC(callee) + "()"
	}

	g.emitLine("%s;", callStr)
	return nil
}

// genPrintCall генерирует printf для встроенной функции print().
func (g *Generator) genPrintCall(args []*parser.ASTNode) error {
	for _, arg := range args {
		fmtStr, val := g.printFormatArg(arg)
		g.emitLine("printf(\"%s\\n\", %s);", fmtStr, val)
	}
	return nil
}

// printFormatArg возвращает форматную строку и значение для printf.
func (g *Generator) printFormatArg(node *parser.ASTNode) (string, string) {
	expr := g.exprToC(node)

	// Полевой доступ: player.health → %d
	if node.Type == parser.NodeFieldAccess {
		// Смотрим родительскую структуру чтобы определить тип поля
		return "%d", expr
	}

	// Идентификатор — смотрим тип в scope
	if node.Type == parser.NodeIdent {
		cType := g.lookupVarType(node.Name)
		switch {
		case cType == "char*" || cType == "string":
			return "%s", expr
		case cType == "float":
			return "%f", expr
		default:
			return "%d", expr
		}
	}

	// Число
	if node.Type == parser.NodeNumber {
		if strings.Contains(node.Value, ".") {
			return "%f", expr
		}
		return "%d", expr
	}

	return "%d", expr
}

// genIfStmt генерирует if-блок с новым scope и RAII-деструкторами при выходе.
func (g *Generator) genIfStmt(node *parser.ASTNode) error {
	cond := "1"
	if len(node.Children) > 0 {
		cond = g.exprToC(node.Children[0])
	}

	g.emitLine("if (%s) {", cond)
	g.indent++

	// Новый scope для if-блока
	g.pushScope()

	for _, stmt := range node.Body {
		if err := g.genStmt(stmt); err != nil {
			return err
		}
	}

	// RAII: деструкторы только локальных переменных, созданных внутри if
	g.emitDestructors()
	g.popScope()

	g.indent--
	g.emitLine("}")
	return nil
}

// --- Выражения в C-строку ---

// exprToC преобразует AST-выражение в C-строку.
func (g *Generator) exprToC(node *parser.ASTNode) string {
	if node == nil {
		return ""
	}
	switch node.Type {
	case parser.NodeIdent:
		return node.Name
	case parser.NodeNumber:
		return node.Value
	case parser.NodeFieldAccess:
		// Структуры используют -> для доступа к полям через указатель
		left := g.exprToC(node.Children[0])
		return fmt.Sprintf("%s->%s", left, node.Name)
	case parser.NodeCallExpr:
		return g.callExprToC(node)
	default:
		return node.Name
	}
}

func (g *Generator) callExprToC(node *parser.ASTNode) string {
	if len(node.Children) == 0 {
		return ""
	}
	callee := node.Children[0]
	args := node.Children[1:]
	funcName := g.exprToC(callee)
	return g.functionCallString(funcName, args)
}

func (g *Generator) functionCallString(name string, args []*parser.ASTNode) string {
	argStrs := g.argsToC(args)
	return fmt.Sprintf("%s(%s)", name, strings.Join(argStrs, ", "))
}

func (g *Generator) argsToC(args []*parser.ASTNode) []string {
	var result []string
	for _, arg := range args {
		result = append(result, g.exprToC(arg))
	}
	return result
}

// --- Scope-управление (RAII) ---

func (g *Generator) pushScope() {
	g.scopeStack = append(g.scopeStack, []scopeEntry{})
}

func (g *Generator) popScope() {
	if len(g.scopeStack) > 1 {
		g.scopeStack = g.scopeStack[:len(g.scopeStack)-1]
	}
}

// pushVar добавляет переменную в текущий scope.
func (g *Generator) pushVar(name, cType string, isParam bool) {
	idx := len(g.scopeStack) - 1
	entry := scopeEntry{
		name:       name,
		cType:      cType,
		structName: g.extractStructName(cType),
		isParam:    isParam,
	}
	g.scopeStack[idx] = append(g.scopeStack[idx], entry)
}

func (g *Generator) extractStructName(cType string) string {
	t := strings.TrimSuffix(cType, "*")
	t = strings.TrimSpace(t)
	// Только если у структуры есть кастомный деструктор
	if g.destructors[t] {
		return t
	}
	// Если это структура без деструктора — вернём имя чтобы вызвать free()
	// Но только если это не примитив
	if !isPrimitive(t) && t != "" && !isPrimitive(cType) {
		return t
	}
	return ""
}

// lookupVarType ищет C-тип переменной по имени во всех фреймах (сверху вниз).
func (g *Generator) lookupVarType(name string) string {
	for i := len(g.scopeStack) - 1; i >= 0; i-- {
		for _, entry := range g.scopeStack[i] {
			if entry.name == name {
				return entry.cType
			}
		}
	}
	return ""
}

// emitDestructors выгружает деструкторы текущего фрейма в обратном порядке (LIFO).
// Пропускает параметры функций и примитивные типы.
func (g *Generator) emitDestructors() {
	if len(g.scopeStack) == 0 {
		return
	}
	frame := g.scopeStack[len(g.scopeStack)-1]
	for i := len(frame) - 1; i >= 0; i-- {
		entry := frame[i]
		// Пропускаем параметры функций — их не нужно очищать
		if entry.isParam {
			continue
		}
		// Пропускаем примитивные типы — их не нужно free'шить
		if isPrimitive(entry.cType) {
			continue
		}
		if entry.structName != "" {
			// Проверяем есть ли кастомный деструктор
			if g.destructors[entry.structName] {
				g.emitLine("%s_del(%s);", entry.structName, entry.name)
			} else if !isPrimitive(entry.structName) {
				// Структура без деструктора — просто free
				g.emitLine("free(%s);", entry.name)
			}
		} else if !isPrimitive(entry.cType) && entry.cType != "" {
			// Указатель на что-то без известного деструктора
			g.emitLine("free(%s);", entry.name)
		}
	}
	g.scopeStack[len(g.scopeStack)-1] = nil
}

func isPrimitive(cType string) bool {
	switch cType {
	case "int", "float", "char*", "double", "string", "bool":
		return true
	}
	return false
}

// --- Утилиты ---

func (g *Generator) emitLine(format string, args ...interface{}) {
	indent := strings.Repeat("    ", g.indent)
	line := fmt.Sprintf(format, args...)
	g.output.WriteString(indent)
	g.output.WriteString(line)
	g.output.WriteString("\n")
}

func codexTypeToC(ct string) string {
	switch ct {
	case "int":
		return "int"
	case "float":
		return "float"
	case "string":
		return "char*"
	case "bool":
		return "int"
	default:
		return ct + "*"
	}
}
