// Generated by CodeX compiler
#include <stdlib.h>
#include <stdio.h>

typedef struct {
    char* name;
    int health;
    float x;
    float y;
} Player;

void Player_del(Player* self) {
    printf("%d\n", 999);
}

void main() {
    Player* player = (Player*)malloc(sizeof(Player));
    if (player->health) {
        int temp = 123;
        printf("%d\n", temp);
        printf("%d\n", player->health);
    }
    printf("%d\n", player->x);
    Player_del(player);
}

